packages:
  - apps/**
  - leyman/*
  - tools/*
  - '!**/src/tests/**'

catalog:
  '@biomejs/biome': ^2.3.11
  '@eslint/js': ^9.29.0
  '@nx/devkit': ^21.2.1
  '@nx/js': ^21.2.1
  '@pnpm/find-workspace-dir': ^7.0.3
  '@pnpm/lockfile.fs': ^1.1.0
  '@pnpm/lockfile.pruner': ^0.0.6
  '@pnpm/logger': ^5.2.0
  '@swc/cli': ^0.7.7
  '@swc/core': ^1.12.3
  '@swc/helpers': ^0.5.17
  '@tanstack/react-query': ^4.36.1
  '@testing-library/react-hooks': ^8.0.1
  '@types/chai': ^5.2.2
  '@types/chai-as-promised': ^8.0.2
  '@types/eslint': ^9.6.1
  '@types/mocha': ^10.0.10
  '@types/node': ^24.0.3
  '@types/react': ^18.3.18
  '@types/sinon': ^17.0.4
  '@types/tmp': ^0.2.6
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.34.1
  '@typescript-eslint/parser': ^8.34.1
  '@typescript-eslint/utils': ^8.34.1
  ajv: ^8.17.1
  c8: ^10.1.3
  chai: ^5.2.0
  chai-as-promised: ^8.0.1
  change-case: ^5.4.4
  ci-info: ^4.2.0
  comment-json: ^4.2.5
  escape-string-regexp: ^5.0.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.5
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsdoc: ^51.0.3
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-n: ^17.20.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-sonarjs: ^3.0.5
  eslint-plugin-unicorn: ^59.0.1
  eta: ^3.5.0
  expect-type: ^1.2.1
  fast-equals: ^5.2.2
  find-up: ^7.0.0
  globby: ^14.1.0
  mocha: ^11.7.0
  npm: ^11.4.2
  nx: ^21.2.1
  p-defer: ^4.0.1
  prettier: ^3.5.3
  react: ^18.3.1
  react-dom: ^18.3.1
  react-test-renderer: ^18.3.1
  sinon: ^21.0.0
  tmp-promise: ^3.0.3
  ts-dedent: ^2.2.0
  typescript: ^5.8.3
  uint8array-extras: ^1.4.0
  yargs: ^18.0.0

catalogs:
  leyman:
    npm-barrelify: npm:barrelify@^1.3.3
    npm-juniper: npm:juniper@^1.2.5
    npm-pnpm-dedicated-lockfile: npm:pnpm-dedicated-lockfile@^0.0.4
    npm-populate-files: npm:populate-files@^0.2.4
