packages:
  - apps/**
  - leyman/*
  - tools/*
  - '!**/src/tests/**'

catalogs:
  # Local packages that are instead installed from npm to avoid circular dependencies
  leyman:
    npm-barrelify: npm:barrelify@^1.3.2
    npm-default-import: npm:default-import@^2.0.7
    npm-entry-script: npm:entry-script@^3.0.8
    npm-format-file: npm:format-file@^0.1.4
    npm-haywire: npm:haywire@^0.1.7
    npm-haywire-launcher: npm:haywire-launcher@^0.1.10
    npm-iso-crypto: npm:iso-crypto@^1.2.3
    npm-juniper: npm:juniper@^1.2.4
    npm-load-populate-files: npm:load-populate-files@^0.1.1
    npm-mocha-chain: npm:mocha-chain@0.0.10
    npm-nx-update-ts-references: npm:nx-update-ts-references@^0.2.0
    npm-parse-cwd: npm:parse-cwd@^1.1.1
    npm-populate-files: npm:populate-files@^0.2.3
    npm-sinon-typed-stub: npm:sinon-typed-stub@0.0.10

catalog:
  '@biomejs/biome': ^1.9.4
  '@eslint/js': ^9.17.0
  '@nx/devkit': ^20.3.2
  '@pnpm/find-workspace-dir': ^7.0.3
  '@pnpm/lockfile.fs': ^1.1.0
  '@pnpm/lockfile.pruner': ^0.0.6
  '@pnpm/logger': ^5.2.0
  '@swc/cli': ^0.5.2
  '@swc/core': ^1.10.4
  '@swc/helpers': ^0.5.15
  '@tanstack/react-query': ^4.36.1
  '@testing-library/react-hooks': ^8.0.1
  '@types/chai': ^5.0.1
  '@types/chai-as-promised': ^8.0.1
  '@types/eslint': ^9.6.1
  '@types/mocha': ^10.0.10
  '@types/node': ^22.10.5
  '@types/react': ^18.3.18
  '@types/sinon': ^17.0.3
  '@types/tmp': ^0.2.6
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^8.19.0
  '@typescript-eslint/parser': ^8.19.0
  '@typescript-eslint/utils': ^8.19.0
  ajv: ^8.17.1
  c8: ^10.1.3
  chai: ^5.1.2
  chai-as-promised: ^8.0.1
  change-case: ^5.4.4
  ci-info: ^4.1.0
  comment-json: ^4.2.5
  escape-string-regexp: ^5.0.0
  eslint: ^9.17.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsdoc: ^50.6.1
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-n: ^17.15.1
  eslint-plugin-react: ^7.37.3
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-sonarjs: ^3.0.1
  eslint-plugin-unicorn: ^56.0.1
  eta: ^3.5.0
  expect-type: ^1.1.0
  fast-equals: ^5.1.3
  find-up: ^7.0.0
  globby: ^14.0.2
  mocha: ^11.0.1
  npm: ^11.0.0
  nx: ^20.3.2
  p-defer: ^4.0.1
  prettier: ^3.4.2
  react: ^18.3.1
  react-dom: ^18.3.1
  react-test-renderer: ^18.3.1
  sinon: ^19.0.2
  tmp-promise: ^3.0.3
  ts-dedent: ^2.2.0
  typescript: ^5.7.2
  uint8array-extras: ^1.4.0
  yargs: ^17.7.2
