import pDefer from 'p-defer';
import { HookOrderError } from './errors.js';
import { mergeContexts } from './merge-context.js';

/**
 * Callback provided by the end user to a hook or test.
 *
 * Its real signature (e.g. `this` binding, `done` callbacks, framework context parameters)
 * is only known to the framework adapter, so it is left opaque here.
 */

export type UserCallback = (this: any, ...args: any[]) => unknown;

/**
 * Framework-agnostic view of a single hook/test execution.
 *
 * @template Key - identity of a test
 */
export interface Invocation<Key> {
    /**
     * Identity of the currently executing test.
     *
     * Used to propagate per-test context from `beforeEach` hooks to tests and `afterEach` hooks.
     * Irrelevant for one-time hooks (`before`/`after`).
     */
    readonly key: Key;
    /**
     * Invoke the user's callback with the propagated context,
     * plus whatever framework-specific arguments/bindings the adapter supplies.
     */
    readonly call: (ctx: object) => unknown;
}

/**
 * Core logic to execute when the framework runs a hook/test.
 *
 * @template Key - identity of a test
 */
export type Handler<Key> = (invocation: Invocation<Key>) => Promise<void>;

/**
 * Registers a hook with the underlying framework.
 *
 * The adapter is responsible for creating a native callback that invokes `handler`,
 * and for reporting any failure of `handler` to the framework.
 *
 * @template Key - identity of a test
 */
export type HookRegistrar<Key> = (
    title: string | undefined,
    cb: UserCallback,
    handler: Handler<Key>
) => unknown;

/**
 * Registers a test with the underlying framework.
 *
 * Return value is passed through to the caller as-is (e.g. Mocha's `Test` instance).
 *
 * @template Key - identity of a test
 */
export type TestRegistrar<Key> = (
    title: string,
    cb: UserCallback,
    handler: Handler<Key>
) => unknown;

export type HookArgs = [string, UserCallback] | [UserCallback];

/**
 * Lookup of context by test.
 *
 * While implemention is recommended to be a WeakMap, technically it can be anything that implements `get`.
 * This is useful for cases like entrypoint and one-time mapping, which will return the same value regardless
 * of what "key" is provided.
 *
 * @template Key - identity of a test
 */
export type ContextMap<Key> = Pick<WeakMap<object & Key, Promise<object>>, 'get'>;

const parseHookArgs = (args: HookArgs): [string | undefined, UserCallback] =>
    args.length === 1 ? [undefined, args[0]] : args;

/**
 * Context produced by a one-time hook.
 *
 * `started` is tracked so that downstream hooks can detect they are executing out of order,
 * which would otherwise wait forever on a context that will never resolve.
 */
export interface OneTimeContext {
    readonly started: boolean;
    readonly context: Promise<object>;
}

/**
 * Before/After hooks run only once in the lifecycle of tests.
 *
 * Therefore the incoming context is a single promise, and it will emit a single promise.
 *
 * If the hook fails, downstream hooks (e.g. `after`) still receive the incoming context.
 *
 * @param checkLock - asserts no hook/test is currently executing
 * @param registrar - registers the hook with the framework
 * @param existing - context generated by previous hooks
 * @param args - arguments passed to hook, optionally with a title and callback
 * @returns merged context between existing and extra context created in this hook
 */
export const wrapOneTimeHook = (
    checkLock: () => void,
    registrar: HookRegistrar<unknown>,
    existing: OneTimeContext,
    args: HookArgs
): OneTimeContext => {
    checkLock();

    const [title, cb] = parseHookArgs(args);

    const deferred = pDefer<unknown>();
    const result = {
        started: false,
        context: mergeContexts(existing.context, deferred.promise as Promise<object | undefined>),
    };

    registrar(title, cb, async ({ call }) => {
        // Set synchronously, before any await, so that hooks executed concurrently can observe it.
        result.started = true;
        if (!existing.started) {
            throw new HookOrderError();
        }
        try {
            deferred.resolve(await call({ ...(await existing.context) }));
        } catch (err) {
            deferred.resolve(undefined);
            throw err;
        }
    });

    return result;
};

/**
 * BeforeEach/AfterEach hooks run for each test.
 *
 * Therefore the incoming context is mapped by test, and will similarly emit context in a map.
 *
 * If the hook fails, downstream hooks (e.g. `afterEach`) still receive the incoming context.
 *
 * @template Key - identity of a test
 * @param checkLock - asserts no hook/test is currently executing
 * @param registrar - registers the hook with the framework
 * @param existingMap - lookup of test to context generated by previous hooks
 * @param args - arguments passed to hook, optionally with a title and callback
 * @returns map of test to merged context
 */
export const wrapPerTestHook = <Key>(
    checkLock: () => void,
    registrar: HookRegistrar<Key>,
    existingMap: ContextMap<Key>,
    args: HookArgs
): WeakMap<object & Key, Promise<object>> => {
    checkLock();

    const [title, cb] = parseHookArgs(args);

    // A new map is initiated per call to beforeEach/afterEach, and populated as each test executes.
    const testToContext = new WeakMap<object & Key, Promise<object>>();

    registrar(title, cb, async ({ key, call }) => {
        // Populate synchronously, before any await, so that downstream hooks always find an entry
        // once this hook has started. This matters for:
        // - `done`-style callbacks, where the framework may move on before the callback has returned
        // - Frameworks that start hooks concurrently
        const deferred = pDefer<object>();
        testToContext.set(key as object & Key, deferred.promise);

        const existingContext = existingMap.get(key as object & Key);
        if (!existingContext) {
            throw new HookOrderError();
        }
        const existing = await existingContext;
        try {
            const additional = await call({ ...existing });
            deferred.resolve(await mergeContexts(existing, additional as object | undefined));
        } catch (err) {
            deferred.resolve(existing);
            throw err;
        }
    });

    return testToContext;
};

/**
 * Tests will load the context from the map, and pass that onto the provided test callback.
 *
 * @param checkLock - asserts no hook/test is currently executing
 * @param registrar - registers the test with the framework
 * @param existingMap - lookup of test to context generated by previous hooks
 * @param title - name of test
 * @param cb - test callback provided by user
 * @returns whatever the framework returns when registering a test
 */
export const wrapTest = <Key>(
    checkLock: () => void,
    registrar: TestRegistrar<Key>,
    existingMap: ContextMap<Key>,
    title: string,
    cb: UserCallback
): unknown => {
    checkLock();

    return registrar(title, cb, async ({ key, call }) => {
        const existing = (await existingMap.get(key as object & Key))!;
        await call({ ...existing });
    });
};

/**
 * Hooks/tests that are used as the "entrypoint" (not propagating any context)
 * should not provide the context as a parameter to the callback (for simplicity).
 *
 * Wrap the callback in another that strips out the context.
 *
 * The wrapper reports one more parameter than the original callback,
 * as some frameworks (e.g. Mocha) inspect callback arity to detect `done` usage.
 *
 * @param cb - callback provided by user, that does not expect a context
 * @returns callback that accepts (and ignores) a leading context parameter
 */
export const withoutContext = (cb: UserCallback): UserCallback => {
    const wrapped = function (this: unknown, _ctx: object, ...args: unknown[]): unknown {
        return cb.apply(this, args);
    };
    Object.defineProperty(wrapped, 'length', { value: cb.length + 1 });
    return wrapped;
};
