version: '3.8'

services:
  leyman:
    build:
      context: .
      dockerfile: Dockerfile

    entrypoint:
      - /usr/local/share/docker-init.sh

    volumes:
      - ..:/workspace:delegated

    # Overrides default command so things don't shut down after the process ends.
    command:
      - sleep
      - infinity
