import type { DeferredPromise } from 'p-defer';
import type { BindingOutputType, GenericBinding, InstanceBinding } from '#binding';
import type {
    GenericBaseHaywireId,
    GenericHaywireId,
    GenericOutputHaywireId,
    HaywireIdType,
    OutputHaywireId,
    RawType,
    StripAnnotations,
} from '#identifier';
import type { Scopes } from '#scopes';
import type { Extendable, InstanceOfClass, InvalidInput, IsClass, NonExtendable } from '#types';
import pDefer from 'p-defer';
import { normalizeOutputId, TempBinding } from '#binding';
import {
    HaywireCircularDependencyError,
    HaywireDuplicateOutputError,
    HaywireInstanceOfResponseError,
    HaywireListResponseError,
    HaywireMultiError,
    HaywireNullResponseError,
    HaywireProviderMissingError,
    HaywireSyncSupplierError,
    HaywireUndefinedResponseError,
} from '#errors';
import { expandOutputId, expandSharedOutputIds, unsafeIdentifier } from '#identifier';
import {
    eagerRequestScope,
    eagerSingletonScope,
    isolatedRequestScope,
    requestScope,
    singletonScope,
    transientScope,
} from '#scopes';

/**
 * Used during deferred instantiations, as a way to provide references to
 * "this already exists in request chain, so can re-use it".
 */
type DeferredCache = Map<
    GenericBaseHaywireId,
    {
        value: unknown;
    }
>;
/**
 * Cached values for scope, to prevent re-instantiations.
 *
 * Async version will rely on the `promise`, which will resolve to the `value`.
 * Sync version will just rely on the `value` and populate an auto-resolving promise
 * (and we generally protect against the possibility that sync version will try to access value before populated).
 *
 * Note that the `promise` wraps the value in a tuple, in order to prevent accidentally merging with the raw value
 * in the case that it is a promise itself (not a recommended pattern, but supported nonetheless).
 */
type ScopeCache = Map<
    GenericBinding,
    {
        promise?: Promise<readonly [unknown]>;
        value?: unknown;
    }
>;
/**
 * Generated by a binding to bubble up to top-level request.
 * Extends a deferred promise that is expected to be resolved with the late-bound value, or rejected
 * with any errors that pop up in the meantime.
 *
 * The registry will be populated by instances that are created in the chain, so that _eventually_ that value
 * can be re-used when requested during deferred.
 */
interface DeferredRequest extends DeferredPromise<unknown> {
    binding: GenericBinding;
    dependencyId: GenericHaywireId;
    registry: DeferredCache;
}

/**
 * Merge the results of the requested binding(s) into the requested value.
 *
 * For a list request (multiple bindings) the full list is registered to every deferred request
 * generated in the chain, as the individual list bindings only register their own portion.
 *
 * @param bindings - requested binding(s)
 * @param listValue - value generated for each binding, in order
 * @param deferredRequests - deferred requests generated in the chain
 * @returns single value, or flattened list of values
 */
const collectRequestedValue = (
    bindings: GenericBinding | readonly GenericBinding[],
    listValue: unknown[],
    deferredRequests: DeferredRequest[]
): unknown => {
    if (!Array.isArray(bindings)) {
        return listValue[0];
    }
    const value = listValue.flat();
    // List requests always contain at least one binding, all sharing the same base id.
    const baseId = (bindings as readonly GenericBinding[])[0]!.outputId.baseId();
    for (const { registry } of deferredRequests) {
        registry.set(baseId, { value });
    }
    return value;
};

export type MaybeSyncContainer<
    Outputs extends [Extendable],
    Async extends boolean,
> = Async extends true ? Container<Outputs> : SyncContainer<Outputs>;

export type ExpandedContainer<
    Outputs extends [Extendable],
    Bindings extends GenericBinding,
    Async extends boolean,
> = MaybeSyncContainer<BindingOutputType<Bindings['outputId']> | Outputs, Async>;

type NoBindingDeclared = [InvalidInput<'NoBindingDeclared'>];

declare const typeTracking: unique symbol;
const createContainerSym = Symbol('createContainer');
const preloadSyncSym = Symbol('preloadSync');
const getSyncSym = Symbol('getSync');
const addBoundInstancesSym = Symbol('addBoundInstances');
const getIdToBindingSym = Symbol('getIdToBinding');
const getIdToListBindingsSym = Symbol('getIdToListBindings');

/**
 * TODO: Current generic logic accidentally computes this as false
 * Wrap in helper to handle type casting and just check the list field.
 *
 * @param id - output/dependency id
 * @returns is list id
 */
const checkIsList = (id: GenericHaywireId): boolean => id.annotations.list !== false;

const validateOutputElement = (outputId: GenericOutputHaywireId, value: unknown): void => {
    if (value === null) {
        if (!outputId.annotations.nullable) {
            throw new HaywireNullResponseError(outputId);
        }
    } else if (value === undefined) {
        if (!outputId.annotations.undefinable) {
            throw new HaywireUndefinedResponseError(outputId);
        }
    } else if (outputId.construct && !(value instanceof outputId.construct)) {
        throw new HaywireInstanceOfResponseError(outputId, value);
    }
};

/**
 * Validate the value generated by a binding's provider against the declared output
 * (e.g. null but output is not nullable).
 *
 * List outputs are always an array (see `providerToMaybeList`), and each element is validated individually.
 *
 * @param outputId - binding output id
 * @param value - value generated by provider
 * @throws when the value does not satisfy the output id
 */
const validateProviderOutput = (outputId: GenericOutputHaywireId, value: unknown): void => {
    // TODO move these checks into binding instead
    if (checkIsList(outputId)) {
        if (!Array.isArray(value)) {
            throw new HaywireListResponseError(outputId, value);
        }
        for (const element of value) {
            validateOutputElement(outputId, element);
        }
    } else {
        validateOutputElement(outputId, value);
    }
};

/**
 * Container that will be wired to generate instances on demand.
 * Supports async providers externally, and sync providers internally
 * (either via suppliers or the extended {@link SyncContainer} class).
 *
 * Type declarations on the class are based on all the possible allowed inputs
 * (e.g. if based on a binding of Foo, there are entries for both Foo + Foo | null).
 *
 * This typing should be considered an internal implementation, and not hard-coded in
 * any way.
 *
 * Instances of containers are not created directly, and should be implemented via `createContainer`
 * which will use an underlying `Module` and perform the necessary checks to ensure that all
 * necessary bindings exist.
 *
 * Using a container comes in four steps.
 * 1) Checking
 *    - Optional step, although produces potentially unsafe code.
 *    - Should only be skipped if checks are performed elsewhere (e.g. during unit tests).
 * 2) Wiring
 *    - Sets up the actual data flow to generate instances based on scopes and suppliers.
 *    - Will perform checks, if not explicitly performed already
 * 3) Preload
 *    - Instantiates any eager singletons
 *    - Will perform wiring, if not explicitly performed already
 * 4) Get
 *    - Main use case of container. Used for actual instantiation, and can be used to continue to create more instances.
 *    - Will perform preload, if not explicitly performed already.
 *
 * @template Outputs
 */
export class Container<Outputs extends [Extendable]> {
    public declare [typeTracking]: Outputs;
    readonly #isSync: boolean;
    /**
     * All bindings found in the original modules, merging both non-list and all list.
     */
    readonly #bindings: ReadonlySet<GenericBinding>;
    /**
     * Binding mapped by the base id of the output
     */
    readonly #baseIdToBinding: ReadonlyMap<GenericBaseHaywireId, GenericBinding>;
    /**
     * List bindings mapped by shared based if of output
     */
    readonly #baseIdToListBindings: ReadonlyMap<GenericBaseHaywireId, readonly GenericBinding[]>;
    #checked: boolean;
    #wired: boolean;
    /**
     * Map of binding to all bindings in the possible request scope that are singletons.
     * Only set with singleton bindings.
     */
    readonly #singletonMap: Map<GenericBinding, readonly GenericBinding[]>;
    /**
     * Map of binding to all bindings that directly depend on it. Only populated for singletons.
     * Populated during wiring.
     *
     * Effectively inverse of `singletonMap`
     */
    readonly #upstreamDependents: Map<GenericBinding, Set<GenericBinding>>;
    /**
     * Map of binding, to all bindings that must first be "eagerly requested".
     * An entry exists for all bindings, but many will result in an empty array.
     *
     * Populated during the "wire" step.
     */
    readonly #requestMap: Map<GenericBinding, readonly GenericBinding[]>;
    /**
     * Map of binding, to a boolean determining whether it must be requested asynchronously.
     * Async bindings are the most obvious, but a "sync" binding that directly depends on another async binding
     * will not actually be available synchronously.
     * Unless that async binding was created as an "eager singleton".
     *
     * An entry exists for all bindings.
     * Populated during the "wire" step.
     */
    readonly #isAsyncImplementationMap: Map<GenericBinding, boolean>;
    /**
     * Cache of singleton instances for the binding. Shared across every request,
     * and becomes populated over time.
     */
    readonly #singletonCache: ScopeCache = new Map();
    #preloaded: Promise<void> | null = null;

    /**
     * Binding mapped by every possible valid id (same non-null binding will be present under both null and non-null ids).
     */
    readonly #idToBinding: ReadonlyMap<GenericOutputHaywireId, GenericBinding>;
    /**
     * List bindings mapped by every possible valid id.
     * The ids will be the intersection of all valid ids.
     */
    readonly #idToListBindings: ReadonlyMap<GenericOutputHaywireId, readonly GenericBinding[]>;

    /**
     * Create a container based on a map of bindings (coming from a module)
     * or from another container to be cloned.
     *
     * If input is map of bindings, populate datasets with binding data and defer to future user interaction for
     * checking/wiring/preloading.
     *
     * If input is exiting container, shallow copy all internal datasets _except_ singleton caches.
     * So if a wired container will remain wired after clone.
     * Note that in order to properly clone a SyncContainer, the SyncContainer constructor must be called first.
     *
     * @param params - Either a container to clone, or two values:
     *  1) map of id->binding or container
     *  2) map of base id to list bindings, providing multiple providers for list outputs
     */
    protected constructor(
        ...params:
            | readonly [
                  ReadonlyMap<GenericBaseHaywireId, GenericBinding>,
                  ReadonlyMap<GenericBaseHaywireId, readonly GenericBinding[]>,
              ]
            | readonly [Container<Outputs>]
    ) {
        if (params.length === 1) {
            const [container] = params;
            this.#bindings = new Set(container.#bindings);
            this.#baseIdToBinding = new Map(container.#baseIdToBinding);
            this.#baseIdToListBindings = new Map(container.#baseIdToListBindings);

            this.#idToBinding = new Map(container.#idToBinding);
            this.#idToListBindings = new Map(container.#idToListBindings);

            this.#upstreamDependents = new Map(container.#upstreamDependents);

            this.#isSync = container.#isSync;
            this.#checked = container.#checked;
            this.#wired = container.#wired;

            this.#singletonMap = new Map(container.#singletonMap);
            this.#requestMap = new Map(container.#requestMap);
            this.#isAsyncImplementationMap = new Map(container.#isAsyncImplementationMap);
        } else {
            const [baseIdToBinding, baseIdToListBindings] = params;
            this.#bindings = new Set(
                [...baseIdToBinding.values(), ...baseIdToListBindings.values()].flat()
            );
            this.#baseIdToBinding = new Map(baseIdToBinding);
            this.#baseIdToListBindings = new Map(baseIdToListBindings);

            this.#idToBinding = new Map(
                [...baseIdToBinding.values()].flatMap(binding =>
                    [...expandOutputId(binding.outputId)].map(id => [id, binding])
                )
            );
            this.#idToListBindings = new Map(
                [...baseIdToListBindings].flatMap(([baseId, listBindings]) =>
                    [
                        ...expandSharedOutputIds(
                            baseId,
                            listBindings.map(listBinding => listBinding.outputId)
                        ),
                    ].map(outputListId => [outputListId, listBindings])
                )
            );

            this.#upstreamDependents = new Map();

            this.#isSync = [...this.#bindings].every(binding => !binding.isAsync);
            this.#checked = false;
            this.#wired = false;

            this.#singletonMap = new Map();
            this.#requestMap = new Map();
            this.#isAsyncImplementationMap = new Map();
        }
    }

    /**
     * Exposed to module to create container in protected type-safe way.
     *
     * @param bindings - module bindings
     * @param listBindings - map of base id to list bindings
     * @returns type-safe async container
     */
    public static [createContainerSym]?<Outputs extends [Extendable]>(
        bindings: ReadonlyMap<GenericBaseHaywireId, GenericBinding>,
        listBindings: ReadonlyMap<GenericBaseHaywireId, readonly GenericBinding[]>
    ): Container<Outputs> {
        return new Container<Outputs>(bindings, listBindings);
    }

    /**
     * Attach a set of bindings to a factory-managed container.
     *
     * A container may have `TempBinding`s included, which are enough to pass checks + wires, but will fail to
     * actually instantiate the necessary instances.
     *
     * The factory will then collect these actual bindings later on, and pass them to the container.
     * The container is cloned internally first (to avoid accidental mutations of the original) then the `TempBinding`s
     * are replaced with `InstanceBindings` (guaranteed to be sync and have no other dependencies).
     *
     * Each `InstanceBinding` is internally spread over the possible outputIds, so callers should only provide a single
     * binding for each output.
     *
     * The existing wiring (_if_ already wired) is updated to point to these new bindings.
     *
     * @param container - Container (both sync or async) with temp bindings
     * @param bindings - list of instance bindings to
     * @returns cloned container with bindings attached
     * @throws {HaywireDuplicateOutputError} When incoming bindings overlap with existing declarations
     */
    public static [addBoundInstancesSym]?<
        Outputs extends [Extendable],
        Bindings extends InstanceBinding<GenericHaywireId>,
        Async extends boolean,
    >(
        container: MaybeSyncContainer<Outputs, Async>,
        bindings: Bindings[]
    ): ExpandedContainer<Outputs, Bindings, Async> {
        const cloned = new (container.constructor as typeof Container | typeof SyncContainer)(
            container
        ) as ExpandedContainer<Outputs, Bindings, Async>;

        for (const binding of bindings) {
            if (checkIsList(binding.outputId)) {
                const existingListBinding = cloned.#baseIdToListBindings.get(
                    binding.outputId.baseId()
                )?.[0];
                if (existingListBinding) {
                    if (existingListBinding instanceof TempBinding) {
                        (cloned.#bindings as Set<GenericBinding>).delete(existingListBinding);

                        if (cloned.#wired) {
                            cloned.#singletonMap.delete(existingListBinding);
                            cloned.#requestMap.delete(existingListBinding);
                            cloned.#isAsyncImplementationMap.delete(existingListBinding);

                            const upstreamDependents =
                                cloned.#upstreamDependents.get(existingListBinding)!;
                            cloned.#upstreamDependents.set(binding, upstreamDependents);
                            const replaceBinding = (
                                arr: readonly GenericBinding[]
                            ): GenericBinding[] =>
                                arr.map(bind => {
                                    if (bind === existingListBinding) {
                                        return binding;
                                    }
                                    return bind;
                                });
                            for (const dependent of upstreamDependents) {
                                cloned.#singletonMap.set(
                                    dependent,
                                    replaceBinding(cloned.#singletonMap.get(dependent)!)
                                );
                            }
                        }

                        cloned.#upstreamDependents.delete(existingListBinding);
                    } else if (cloned.#wired) {
                        // Append to existing list bindings
                        const upstreamDependents =
                            cloned.#upstreamDependents.get(existingListBinding)!;
                        cloned.#upstreamDependents.set(binding, upstreamDependents);

                        for (const dependent of upstreamDependents) {
                            cloned.#singletonMap.set(dependent, [
                                ...cloned.#singletonMap.get(dependent)!,
                                binding,
                            ]);
                        }
                    }

                    const existingListBindings = cloned.#baseIdToListBindings.get(
                        binding.outputId.baseId()
                    )!;
                    // A temp binding is a placeholder for a missing provider; it has already been
                    // pruned from `#bindings`/`#requestMap` above, so it must not linger in the
                    // resolved list (otherwise resolution dereferences a binding with no request map).
                    (
                        cloned.#baseIdToListBindings as Map<
                            GenericBaseHaywireId,
                            readonly GenericBinding[]
                        >
                    ).set(binding.outputId.baseId(), [
                        ...existingListBindings.filter(
                            existing => !(existing instanceof TempBinding)
                        ),
                        binding,
                    ]);
                } else {
                    if (cloned.#wired) {
                        cloned.#upstreamDependents.set(binding, new Set());
                    }
                    (
                        cloned.#baseIdToListBindings as Map<
                            GenericBaseHaywireId,
                            readonly GenericBinding[]
                        >
                    ).set(binding.outputId.baseId(), [binding]);
                }
            } else {
                const existingBinding = cloned.#baseIdToBinding.get(binding.outputId.baseId());
                if (existingBinding) {
                    if (existingBinding instanceof TempBinding) {
                        (cloned.#bindings as Set<GenericBinding>).delete(existingBinding);

                        if (cloned.#wired) {
                            cloned.#singletonMap.delete(existingBinding);
                            cloned.#isAsyncImplementationMap.delete(existingBinding);

                            const upstreamDependents =
                                cloned.#upstreamDependents.get(existingBinding)!;
                            cloned.#upstreamDependents.set(binding, upstreamDependents);
                            const replaceBinding = (
                                arr: readonly GenericBinding[]
                            ): GenericBinding[] =>
                                arr.map(bind => {
                                    if (bind === existingBinding) {
                                        return binding;
                                    }
                                    return bind;
                                });
                            for (const dependent of upstreamDependents) {
                                cloned.#singletonMap.set(
                                    dependent,
                                    replaceBinding(cloned.#singletonMap.get(dependent)!)
                                );
                            }
                            cloned.#upstreamDependents.delete(existingBinding);
                        }
                    } else {
                        // Non-list cannot have overlapping implementations
                        throw new HaywireDuplicateOutputError([binding.outputId.baseId()]);
                    }
                } else if (cloned.#wired) {
                    cloned.#upstreamDependents.set(binding, new Set());
                }

                (cloned.#baseIdToBinding as Map<GenericOutputHaywireId, GenericBinding>).set(
                    binding.outputId.baseId(),
                    binding
                );
            }

            if (checkIsList(binding.outputId)) {
                // Map every valid output id variant to the full set of list bindings, mirroring
                // how the constructor builds `#idToListBindings`. Without this a freshly bound
                // list output would be absent from the map that `getAsync` consults.
                // Ids that are no longer satisfied by _every_ list binding (e.g. a nullable instance was appended)
                // must be removed, so a stricter request cannot receive laxer elements.
                const baseId = binding.outputId.baseId();
                const listBindings = cloned.#baseIdToListBindings.get(baseId)!;
                const outputListIds = expandSharedOutputIds(
                    baseId,
                    listBindings.map(listBinding => listBinding.outputId)
                );
                for (const staleListId of expandOutputId(baseId).difference(outputListIds)) {
                    (
                        cloned.#idToListBindings as Map<
                            GenericOutputHaywireId,
                            readonly GenericBinding[]
                        >
                    ).delete(staleListId);
                }
                for (const outputListId of outputListIds) {
                    (
                        cloned.#idToListBindings as Map<
                            GenericOutputHaywireId,
                            readonly GenericBinding[]
                        >
                    ).set(outputListId, listBindings);
                }
            } else {
                for (const outputId of expandOutputId(binding.outputId)) {
                    (cloned.#idToBinding as Map<GenericOutputHaywireId, GenericBinding>).set(
                        outputId,
                        binding
                    );
                }
            }

            (cloned.#bindings as Set<GenericBinding>).add(binding);

            if (container.#wired) {
                cloned.#singletonMap.set(binding, []);
                cloned.#requestMap.set(binding, []);
                cloned.#isAsyncImplementationMap.set(binding, false);
            }
        }

        return cloned;
    }

    /**
     * Pre-calculate paths for requests to take, so that the actual requests to the container can be determined immediately.
     * Does not actually perform any instantiations.
     *
     * Can safely be called multiple times, and will immediately short circuit successfully after the first.
     *
     * Calls check internally, to ensure container is in a healthy state before continuing.
     *
     * The wiring performed is:
     * Eager Singletons
     *   Eager singletons are tricky becuase despite their _potentially_ async nature, it is always safe to treat them as
     *     sync in other parts of requests. During the very beginning of initialization though, that is not necessarily safe,
     *     so calculate the dependency order in which singletons can be instantiated without causing issues.
     * Eager Requests
     *   Similar to singletons, eager requests can potentially be treated as sync. Again we need to ensure the values
     *     are constructed in the right order to safely access. Also ensures we _only_ eagerly instantiate providers
     *     relevant to this top-level request.
     * Determine which dependencies are safe for async
     *   Where possible, we want to use synchronous instantiation. The logic is overall simpler and more performant. However,
     *     it is not clear based on the binding alone whether or not an instantion can be done syncronously (e.g. has async dependencies)
     *     so this is pre-calculated.
     */
    public wire(): void {
        if (this.#wired) {
            return;
        }

        this.check();

        for (const binding of this.#bindings) {
            this.#upstreamDependents.set(binding, new Set());
        }
        for (const listGroup of this.#baseIdToListBindings.values()) {
            for (const binding of listGroup) {
                this.#upstreamDependents.set(binding, new Set());
            }
        }
        this.#wireSingletons();
        this.#wireRequests();
        this.#wireAsyncs();

        this.#wired = true;
    }

    /**
     * Check internals of container to protect against edge cases that cannot be protected against via traditional type safety.
     *
     * Can safely be called multiple times, and will immediately short circuit successfully after the first.
     *
     * The checks performed are:
     * Ensuring all dependencies have a binding
     *   Ideally module logic protect against this, but it is possible to accidentially re-instantiate an identifier, or to
     *     have classes that _should_ be treated separately, but actually are exact matches in Typescript's duck typing.
     * Protect Circular dependencies
     *   Circular dependencies can be tricky to see directly, as they may be the result of large chains including suppliers.
     *     The type system does not attempt to protect against circulars for this reason, so a check must be performed to ensure
     *     either no circulars exist, or they are properly protected against with deferred dependencies and properly scoped suppliers.
     * Enforce circular suppliers
     *   The top level container will always be async if a single provider internally is async. However the suppliers generated internally
     *     _may_ be sync, if just that dependency path is all sync. The type system is not able to track this directly, because there are
     *     cases of async dependencies that can be treated as sync, because eager scoping will pre-cache the value.
     */
    public check(): void {
        if (this.#checked) {
            return;
        }
        this.#checkForDependenciesOutput();
        this.#checkForCircular();
        this.#checkForAsyncSupplier();

        this.#checked = true;
    }

    /**
     * Pre-calculate all eager singletons.
     *
     * Conceptually it is safe to run multiple times, due to scope caching. Attempts to improve performance
     * by just returning a promise that resolves with a previous `preload`'s success.
     *
     * All singletons are attempted to be invoked in parallel. However the invocation of singleton dependencies
     * is called prior to a single instance, as pre-calculated in `#wireSingletons`, and caching will kick in
     * for following requests.
     *
     * If this is an all sync-container, fall back on the sync version of this method to ensure all instances are
     * cached before the method retuns.
     *
     * Ensures that container is wired before any loading.
     *
     * @returns promise that resolves once all the preloads are complete
     */
    public async preloadAsync(): Promise<void> {
        // Similar to implementation methods, it is important that no `await` occurs until
        // `#preloaded` has been written to, to ensure no race conditions between multiple `preload` calls.
        if (this.#preloaded) {
            return this.#preloaded;
        }

        if (this.#isSync) {
            this.#preload();
            return;
        }
        this.wire();

        this.#preloaded = Promise.resolve()
            .then(async () => {
                const reqScope: ScopeCache = new Map();
                const requestSingleton = async (binding: GenericBinding): Promise<void> => {
                    const dependencies = this.#singletonMap.get(binding)!;
                    await Promise.all(
                        dependencies.map(async dependency => requestSingleton(dependency))
                    );
                    await this.#getMaybeSync(binding, reqScope, reqScope);
                };
                await Promise.all(
                    [...this.#singletonMap.keys()].map(async binding => requestSingleton(binding))
                );
            })
            .catch(async (err: unknown) => {
                this.#preloaded = null;
                throw err;
            });

        return this.#preloaded;
    }

    /**
     * Request an instance from the container.
     *
     * Type-checking enforces that the requested value is actually defined in this container, and translates the requested
     * identifier to instance type.
     *
     * Will attempt to preload any eager singletons, if not already done.
     *
     * @param id - {@link HaywireId} to instantiate
     */
    public getAsync<Id extends GenericHaywireId>(
        id: Id,
        ...invalidInput: [] &
            ([
                NonExtendable<
                    RawType<Id>,
                    Id['construct'],
                    Id['annotations']['named'],
                    Id['annotations']['list'] extends 'multi' | true ? true : false,
                    Id['annotations']['nullable'],
                    Id['annotations']['undefinable']
                >,
            ] extends Outputs
                ? []
                : NoBindingDeclared)
    ): Promise<StripAnnotations<HaywireIdType<Id>, 'deferred' | 'supplier'>>;
    public getAsync<Constructor extends IsClass>(
        clazz: Constructor,
        ...invalidInput: [] &
            ([
                NonExtendable<InstanceOfClass<Constructor>, Constructor, null, false, false, false>,
            ] extends Outputs
                ? []
                : NoBindingDeclared)
    ): Promise<InstanceOfClass<Constructor>>;
    public async getAsync<Id extends GenericHaywireId>(
        idOrClass: Id
    ): Promise<StripAnnotations<HaywireIdType<Id>, 'deferred' | 'supplier'>> {
        const id = normalizeOutputId(unsafeIdentifier(idOrClass));
        const hasBindings = id.annotations.list
            ? this[getIdToListBindingsSym].has(id)
            : this[getIdToBindingSym].has(id);
        if (!hasBindings) {
            throw new HaywireProviderMissingError([id]);
        }
        await this.preloadAsync();
        const requestCache: ScopeCache = new Map();
        return this.#getMaybeSyncId(id, requestCache, requestCache) as Promise<
            StripAnnotations<HaywireIdType<Id>, 'deferred' | 'supplier'>
        >;
    }

    /**
     * Check that every dependency declared in bindings has an equivalent binding declared.
     *
     * For the most part, we are protected against this by strongly-typed modules and container creation, but there are ways to
     * accidentally get around this.
     *
     * The two main ways that type safety may fail (so this check still neeeds to exist):
     * Accidentally redefining the same identifier.
     *   The issue arises from `identifier() !== identifier()`.
     *     So even if the exact same types/names are provided, the actual values seen by javascript are different.
     *   note classes are generally protected from this (`identifier(Foo) === identifier(Foo)`) but can still result in other errors (see second point).
     * Using class constructors for instances that are exact matches via duck-typing.
     *   According to typescript, classes that have the exact same interface are replaceable with eachother.
     *     Often times this is actually desired behavior, but can result in unexpected behavior.
     *     ```
     *     class Foo {
     *         similarValue: 123;
     *     }
     *     class Bar {
     *         similarValue: 123;
     *     }
     *     // Legal!
     *     const x: Foo = new Bar();
     *     ```
     *     As a result, haywire cannot tell the difference between `identifier(Foo)` and `identifier(Bar)`.
     *
     * @throws when a binding declares a dependency that is not found within the container
     */
    #checkForDependenciesOutput(): void {
        const uniqueDependencyIds = new Set(
            [...this.#bindings].flatMap(binding =>
                binding.dependencyIds.map(id =>
                    normalizeOutputId(id.deferred(false).supplier(false))
                )
            )
        );

        const noProviderFoundIds: GenericOutputHaywireId[] = [];

        for (const dependencyId of uniqueDependencyIds) {
            if (checkIsList(dependencyId)) {
                if (!this.#idToListBindings.has(dependencyId)) {
                    noProviderFoundIds.push(dependencyId);
                }
            } else if (!this.#idToBinding.has(dependencyId)) {
                noProviderFoundIds.push(dependencyId);
            }
        }

        if (noProviderFoundIds.length > 0) {
            throw new HaywireProviderMissingError(noProviderFoundIds);
        }
    }

    /**
     * Flag any instances of "illegal" circular dependencies, and throw an error.
     *
     * Circular bindings are defined as cases where in order to create dependency `A`,
     * Haywire must first provide it with an instance of `A` (either directly, or via the chain of sub-dependencies)
     *
     * This is naively impossible, and results in infinite requests for `A`, even if using a scope that
     * can take advantage of caching (because the original request can never return to populate the cache).
     *
     * The best solution is to simply avoid circular dependencies in design.
     *
     * The next best is to utilize "deferred" dependencies. This means the dependency is on a promise that _eventually_ resolves to
     * the requested value.
     *
     * For non-supplier dependencies, a deferred dependency successfully "breaks the chain".
     *
     * e.g. `A` depends on `B` depends on `C` depends on `D`, which _circularly_ depends on `A`.
     * Making any single of these dependencies deferred is enough.
     *
     * For supplier dependencies, this may not be enough.
     *
     * e.g. `A` depends on `B`. `B` depends on deferred `C`. `C` depends on a supplier of `D`. `D` depends on `A`.
     *
     * In order to supply the instance of `C` to `B`, we need to create a supplier of `D`. This _supplier_ can _theoretically_ be used
     * immediately in the provider, which instantiates a _new_ request for `D` (which requests `A`, and `B`!).
     *
     * This is the infinite loop we were trying to avoid.
     *
     * Suppliers are only allowed in a circular dependency when a binding in the chain has a scope that can re-use a previously cached value.
     * That means either a singleton scope, or request scope with propagation.
     *
     * In the example above, if the supplier propagated scope and `B` had been `request scope`d, it would be valid.
     * This is because newly "supplied" instaces of D could fall back on cached version of B instead of re-instanting and infinitely looping.
     *
     * In order to detect these circular dependencies, perform a check for each individual binding.
     * Iterate over each dependency, tracking the current "chain".
     *
     * If we end at a binding with no dependencies, that "chain" is safe.
     * If we end up at a dependency that is _already_ in the chain, end this check (if it is illegally circular, let that binding perform its own check).
     * If we end up at a dependency of our original binding:
     *     If we never crossed a deferred boundary, flag this as circular
     *     Else
     *          If there is a singleton-scoped in the chain, it is safe
     *          If there is a request-scoped in the chain
     *              If never crossed a non-propagating supplier boundary, it is safe
     *              else flag this is as circular
     *
     * We can optimize the _safe_ paths a bit.
     * If we know `A` is not flagged as a circular, then any time `A` comes up in the check, we can immediately declare the chain safe.
     * However we cannot do the same for _unsafe_ paths (which matters less, since performance in the case that eventually throws an error is less important).
     *
     * example: `A` depends on `B`, `B` depends on `C`, and `C` depends on `B`.
     * Both `B` and `C` are unsafe circulars. However this is not `A`'s fault, and should be excluded from the reporting.
     *
     * @throws when dependencies found to be circularly dependenct on themselves. The chains povided are unique.
     */
    #checkForCircular(): void {
        const safeOutputs = new Set<GenericBaseHaywireId>();
        const circularPaths: GenericHaywireId[][] = [];
        const singletonScopes = new Set([eagerSingletonScope, singletonScope]);
        const requestScopes = new Set([eagerRequestScope, requestScope]);

        interface ChainLink {
            // Binding for dependency.
            // In case of lists, each binding is its own link that is evaluated as a separate chain
            binding: GenericBinding;
            // The dependency this binding declares to reach the next link in the chain.
            // A binding with multiple dependencies will result in multiple branching chains.
            outgoing: GenericHaywireId;
        }
        const isChainSafe = (chain: ChainLink[]): boolean => {
            if (chain.some(({ outgoing }) => outgoing.annotations.deferred)) {
                // Only if there is deferred can circular dependencies be acceptable

                if (chain.some(({ binding }) => singletonScopes.has(binding.scope))) {
                    // Singletons will eventually run into cached value, so are safe (regardless of suppliers)
                    return true;
                }

                if (chain.some(({ binding }) => requestScopes.has(binding.scope))) {
                    // Request scopes are safe _only_ if the scope is propagated the entire way.
                    return chain.every(({ binding, outgoing }) => {
                        const { supplier } = outgoing.annotations;
                        if (typeof supplier === 'object') {
                            return (
                                supplier.propagateScope && binding.scope !== isolatedRequestScope
                            );
                        }
                        return true;
                    });
                }

                // If there are no suppliers, this is safe
                return chain.every(({ outgoing }) => outgoing.annotations.supplier === false);
            }
            return false;
        };

        const isOutputSafe = (
            dependencyId: GenericHaywireId,
            evaluatedOutputIds: Set<GenericBaseHaywireId>,
            dependencyChain: ChainLink[]
        ): boolean => {
            const baseId = dependencyId.baseId();
            if (safeOutputs.has(baseId)) {
                return true;
            }

            const bindings = checkIsList(baseId)
                ? this.#baseIdToListBindings.get(baseId)!
                : [this.#baseIdToBinding.get(baseId)!];

            if (evaluatedOutputIds.has(baseId)) {
                // Each link pairs a binding with the edge it declares outward, so the cycle
                // sub-chain is already aligned: its first link is the binding that produces
                // `baseId`, and its last link's `outgoing` is the current `dependencyId` that
                // closes the loop. No re-alignment needed.
                let foundCircular = false;
                const circularChain = [...dependencyChain].filter(link => {
                    if (link.binding.outputId.baseId() === baseId) {
                        foundCircular = true;
                    }
                    return foundCircular;
                });
                if (isChainSafe(circularChain)) {
                    return true;
                }
                circularPaths.push(circularChain.map(link => link.outgoing));
                return false;
            }

            return bindings.every(binding => {
                const evaluatedOutputIdsForBinding = new Set(evaluatedOutputIds);
                evaluatedOutputIdsForBinding.add(baseId);
                let isSafe = true;
                for (const nextDependencyId of binding.dependencyIds) {
                    const dependencyChainForBinding = [
                        ...dependencyChain,
                        { binding, outgoing: nextDependencyId },
                    ];
                    // Evaluate the recursion first (never short-circuit) so that every
                    // dependency is explored and all circular paths are collected, not just
                    // the first unsafe one.
                    isSafe =
                        isOutputSafe(
                            nextDependencyId,
                            evaluatedOutputIdsForBinding,
                            dependencyChainForBinding
                        ) && isSafe;
                }
                return isSafe;
            });
        };

        for (const binding of this.#bindings) {
            const baseId = binding.outputId.baseId();
            if (isOutputSafe(baseId, new Set(), [])) {
                safeOutputs.add(baseId);
            }
        }

        if (circularPaths.length > 0) {
            throw new HaywireCircularDependencyError(circularPaths);
        }
    }

    /**
     * Suppliers are by default synchronous, even if the underlying container is async
     * (although they can be flagged async to avoid this issue altogether).
     *
     * A supplier can be sync when the binding is synchronous and every dependency qualifies as synchronous.
     * It can also be synchronous if async binding or dependencies can utilize eager scopes.
     *
     * Note that deferred does not "protect" a binding from async dependencies.
     * This is because deferred dependencies will resolve by the time the request completes
     * (or rather, immediately on the next event loop, which is the best we can do with promises).
     * So a deferred dependency must resolve syncronously as well.
     *
     * Suppliers that propagate their scope (and are not supplier-scoped themselves) can benefit from eager request bindings,
     * but ones that do not can only rely on eager singletons.
     *
     * We only need to inspect sync suppliers
     * (async suppliers don't have this problem, and regular bindings can obfuscate the instantation logic, the whole point of DI)
     * to see if the dependency chain is safe.
     *
     * Some optimizations can be performed to prevent duplicate checks against suppliers.
     * e.g. both Foo + Bar has dependency on supplier of Baz can re-use the same calculation.
     *
     * @throws When a synchronous supplier is declared for a provider that must be async
     */
    #checkForAsyncSupplier(): void {
        const isSafeForSyncSupplier = (
            binding: GenericBinding,
            chain: Set<GenericOutputHaywireId>,
            eagerScopes: Set<Scopes>
        ): boolean => {
            const baseId = binding.outputId.baseId();
            if (chain.has(baseId)) {
                // Part of circular dependency.
                // If we are sync up until this point, it can remain sync.
                return true;
            }
            if (eagerScopes.has(binding.scope)) {
                // If the "parent" scopes have already eagerly created these resources,
                // will be synchronously available
                return true;
            }
            if (binding.isAsync) {
                // Value cannot guaranteed to be present, even if belonging to "parent" scope.
                return false;
            }
            return binding.dependencyIds.every(dependencyId => {
                const { supplier } = dependencyId.annotations;
                if (typeof supplier === 'object' && (!supplier.propagateScope || !supplier.sync)) {
                    // Either async boundary or separate request.
                    // Separate requests are validated in separate iteration
                    return true;
                }
                const dependencyBaseId = dependencyId.baseId();
                const dependencyBindings = checkIsList(dependencyBaseId)
                    ? this.#baseIdToListBindings.get(dependencyBaseId)!
                    : [this.#baseIdToBinding.get(dependencyBaseId)!];
                // Continue checking dependencies
                return dependencyBindings.every(dependencyBinding =>
                    isSafeForSyncSupplier(
                        dependencyBinding,
                        new Set([...chain, baseId]),
                        eagerScopes
                    )
                );
            });
        };

        const syncSuppliers = [...this.#bindings]
            .flatMap(binding => binding.dependencyIds.map(id => [binding, id] as const))
            .filter(([, dependencyId]) => {
                const { supplier } = dependencyId.annotations;
                return typeof supplier === 'object' && supplier.sync;
            });

        const safeBindings = new Set<GenericBinding>();
        const unsafeBindings = new Set<GenericBinding>();
        const unsafeSupplierBindings: {
            bindingOutputId: GenericOutputHaywireId;
            supplierId: GenericHaywireId;
        }[] = [];
        const addUnsafePair = (
            dependencyBinding: GenericBinding,
            propagateScope: boolean
        ): void => {
            const dependencyBaseId = dependencyBinding.outputId.baseId();
            for (const binding of this.#bindings) {
                for (const depId of binding.dependencyIds) {
                    if (depId.baseId() === dependencyBaseId) {
                        const { supplier } = depId.annotations;
                        if (
                            typeof supplier === 'object' &&
                            supplier.sync &&
                            supplier.propagateScope === propagateScope
                        ) {
                            unsafeSupplierBindings.push({
                                bindingOutputId: dependencyBinding.outputId,
                                supplierId: depId,
                            });
                        }
                    }
                }
            }
        };

        for (const [propagateScope, isIsolatedRequestScope, eagerScopes] of [
            // Suppliers that are the "entrypoint" for a request cannot rely on eager requests
            // to pre-cache async dependencies.
            [false, false, new Set([eagerSingletonScope] as const)],
            [false, true, new Set([eagerSingletonScope] as const)],
            // Suppliers that are _not_ the "entrypoint", but are not inheriting the original request scope cannot rely
            // on eager requests to pre-cache async dependencies.
            [true, true, new Set([eagerSingletonScope] as const)],
            // Suppliers that are the propagating scope from a parent request _can_ rely on eager requests
            // to pre-cache async dependencies.
            [true, false, new Set([eagerRequestScope, eagerSingletonScope] as const)],
        ] as const) {
            const syncBindings = new Set(
                syncSuppliers
                    .filter(
                        ([, id]) =>
                            (
                                id.annotations.supplier as {
                                    propagateScope: boolean;
                                }
                            ).propagateScope === propagateScope
                    )
                    .filter(
                        ([binding]) =>
                            (binding.scope === isolatedRequestScope) === isIsolatedRequestScope
                    )
                    .flatMap(([, id]) => {
                        if (checkIsList(id)) {
                            return this.#baseIdToListBindings.get(id.baseId())!;
                        }
                        return this.#baseIdToBinding.get(id.baseId())!;
                    })
                    .filter(binding => !safeBindings.has(binding) && !unsafeBindings.has(binding))
            );

            for (const syncBinding of syncBindings) {
                if (isSafeForSyncSupplier(syncBinding, new Set(), eagerScopes)) {
                    safeBindings.add(syncBinding);
                } else {
                    unsafeBindings.add(syncBinding);
                    addUnsafePair(syncBinding, propagateScope);
                }
            }
        }

        if (unsafeSupplierBindings.length > 0) {
            throw new HaywireSyncSupplierError(unsafeSupplierBindings);
        }
    }

    /**
     * Precalcuate list of eager singletons that need to be instantiated, before
     * the specified eager singleton can be instantiated.
     *
     * Only populates entries for eager singletons, so possible resulting map is actually empty or
     * has no dependencies declared.
     *
     * Does not actually perform the instantations.
     */
    #wireSingletons(): void {
        const collectBindings = (
            binding: GenericBinding,
            stack: Set<GenericBaseHaywireId>
        ): GenericBinding[] => {
            if (stack.has(binding.outputId.baseId())) {
                return [];
            }

            const collected: GenericBinding[] = [];
            for (const dependencyId of binding.dependencyIds) {
                const { deferred, supplier } = dependencyId.annotations;
                if (deferred || (typeof supplier === 'object' && !supplier.sync)) {
                    continue;
                }
                const dependencyBindings = checkIsList(dependencyId)
                    ? this.#baseIdToListBindings.get(dependencyId.baseId())!
                    : [this.#baseIdToBinding.get(dependencyId.baseId())!];
                for (const dependencyBinding of dependencyBindings) {
                    if (dependencyBinding.scope === eagerSingletonScope) {
                        collected.push(dependencyBinding);
                    } else {
                        collected.push(
                            ...collectBindings(
                                dependencyBinding,
                                new Set([...stack, dependencyId.baseId()])
                            )
                        );
                    }
                }
            }
            return collected;
        };

        for (const binding of [...this.#bindings].filter(
            bind => bind.scope === eagerSingletonScope
        )) {
            const singletonBindings = [...new Set(collectBindings(binding, new Set()))];
            this.#singletonMap.set(binding, singletonBindings);
            for (const singletonBinding of singletonBindings) {
                this.#upstreamDependents.get(singletonBinding)!.add(binding);
            }
        }
    }

    /**
     * Map of binding being requested, to bindings that need to be optimisitcally instantiated first.
     *
     * Applies to both top-level requests, and suppliers that do not propagate scope.
     * (Suppliers that do propagate scope don't need to re-instantiate anything)
     *
     * Will contain entries for every request. This ensures that no extra values are instantiated during
     * a request that are not related to the dependency graph.
     *
     * Does not actually perform the instantiations.
     */
    #wireRequests(): void {
        const collectBindings = (
            binding: GenericBinding,
            stack: Set<GenericBaseHaywireId>
        ): GenericBinding[] => {
            if (stack.has(binding.outputId.baseId())) {
                return [];
            }

            const collected: GenericBinding[] = [];
            for (const dependencyId of binding.dependencyIds) {
                const dependencyBaseId = dependencyId.baseId();
                const dependencyBindings = checkIsList(dependencyId)
                    ? this.#baseIdToListBindings.get(dependencyBaseId)!
                    : [this.#baseIdToBinding.get(dependencyBaseId)!];
                for (const dependencyBinding of dependencyBindings) {
                    if (dependencyBinding.scope === eagerSingletonScope) {
                        continue;
                    } else if (dependencyBinding.scope === eagerRequestScope) {
                        collected.push(dependencyBinding);
                    } else {
                        collected.push(
                            ...collectBindings(
                                dependencyBinding,
                                new Set([...stack, dependencyBaseId])
                            )
                        );
                    }
                }
            }
            return collected;
        };
        for (const binding of this.#bindings) {
            this.#requestMap.set(binding, [...collectBindings(binding, new Set())]);
        }
    }

    /**
     * Calculate whether any binding can be performed syncronously.
     *
     * This mapping is only checked during the async path, as we _prefer_ the sync path for simplicity and performance.
     * The sync path cannot possibly redirect the the async path, so there are checks the protect against that need.
     *
     * Note that whether or not the binding is being referenced via a top-level request, a provider dependency,
     * a deferred request, or a supplier is irrelevant to the logic here.
     *
     * The main difference between enabling sync for suppliers has to do with ability to use request caching,
     * but for the actual provider instantiation the request singletons will already exist regardless of context.
     */
    #wireAsyncs(): void {
        const eagerScopes = new Set([eagerRequestScope, eagerSingletonScope]);
        const isAsync = (binding: GenericBinding, chain: Set<GenericBaseHaywireId>): boolean => {
            if (chain.has(binding.outputId.baseId())) {
                // Come full circle. If nothing in the chain has forced async yet, we can stay sync
                return false;
            }
            const existing = this.#isAsyncImplementationMap.get(binding);
            if (typeof existing === 'boolean') {
                // Try to re-use solved portions when available
                return existing;
            }
            if (binding.isAsync) {
                // This is the only that that actually forces async implementations,
                // but can force all consumers, including seemingly sync proiders depending on deferred dependencies
                this.#isAsyncImplementationMap.set(binding, true);
                return true;
            }
            return binding.dependencyIds.some(dependencyId => {
                if (typeof dependencyId.annotations.supplier === 'object') {
                    // Suppliers are resolved "immediately" so that is sync
                    return false;
                }
                const dependencyBindings = checkIsList(dependencyId)
                    ? this.#baseIdToListBindings.get(dependencyId.baseId())!
                    : [this.#baseIdToBinding.get(dependencyId.baseId())!];
                return dependencyBindings.some(dependencyBinding => {
                    if (eagerScopes.has(dependencyBinding.scope)) {
                        // Eager values are pre-computed, so the actual request can always rely on cache
                        return false;
                    }
                    // Check dependency, appending to chain
                    return isAsync(
                        dependencyBinding,
                        new Set([...chain, binding.outputId.baseId()])
                    );
                });
            });
        };

        for (const binding of this.#bindings) {
            this.#isAsyncImplementationMap.set(binding, isAsync(binding, new Set()));
        }
    }

    /**
     * Asynchronously instantiate a binding. Will create all dependencies first before invoking provider.
     * Supplier will be implemented as as a new internal request for that binding, potentially propagating request scope.
     * Deferred dependencies will be implemented as a deferred promise that will be handled by the top-level request
     * (which will iteratively instantiate each dependency and resolve/reject as necessary).
     *
     * @param params - required params
     * @param params.binding - binding being requested
     * @param params.requestCache - current request cache, shared across entire request
     * @param params.supplierCache - current scope cache, potentially same as requestCache,
     * but should be treated differently based on supplier context and scope
     * @param params.deferredCache - map of any bindings that have been calculated already in the current request chain,
     * which should be re-used if possible.
     * @returns promise of both the instantiated value, and any deferred requests that have been generated by dependencies
     * (and dependencies of dependencies)
     */
    async #getImplementation({
        binding,
        requestCache,
        supplierCache,
        deferredCache,
    }: {
        binding: GenericBinding;
        requestCache: ScopeCache;
        supplierCache: ScopeCache;
        deferredCache: DeferredCache;
    }): Promise<{
        value: unknown;
        deferredRequests: DeferredRequest[];
    }> {
        // Re-use of instances already created in the same request chain (e.g. circular deferred dependencies)
        // is handled by callers, which check `deferredCache` by the requested id before reaching here.
        // List element bindings share a base id with the full list, so they only ever register the full list
        // via those callers, never their own portion.
        const isListBinding = checkIsList(binding.outputId);

        const relevantCache = {
            [transientScope]: null,
            [eagerSingletonScope]: this.#singletonCache,
            [singletonScope]: this.#singletonCache,
            [eagerRequestScope]: requestCache,
            [requestScope]: requestCache,
            [isolatedRequestScope]: supplierCache,
        }[binding.scope];

        // If an instance already exists (or is being created in parallel) in the same request, return that immediately.
        // **NOTE** It is very important that any code that exists between here and the "write to cache" later down
        // is _synchronous_ to prevent any possible race condition between requests and their scoping.
        // Promises generated in the middle will be collected and awaited afterwards.
        if (relevantCache) {
            const cached = relevantCache.get(binding);
            if (cached) {
                const [value] = await cached.promise!;
                return {
                    value,
                    deferredRequests: [],
                };
            }
        }

        // Create the value that will be put in cache immediately. Will be necessary to check during deferred rejections
        // to safely evict from cache.
        const cacheContainer = {};

        const deferredRequests: DeferredRequest[] = [];

        // Setup a collection of promises that will be extended by every deferred.
        // Will be used later during the caching to ensure the cache can't resolve until the deferred dependencies resolve.
        const deferredPromises: Promise<unknown>[] = [];

        // Collect a promise that will resolve with the (wrapped) value, but don't actually
        // await it until we get the cache setup.
        const outputPromise = (async () => {
            const settled = await Promise.allSettled(
                binding.dependencyIds.map(async (dependencyId): Promise<readonly [unknown]> => {
                    if (dependencyId.annotations.deferred) {
                        const deferred = pDefer();
                        deferredPromises.push(deferred.promise);
                        const registry: DeferredCache = new Map();
                        deferredRequests.push({
                            ...deferred,
                            binding,
                            dependencyId,
                            registry,
                        });
                        return [deferred.promise];
                    }

                    const dependency = await this.#getIdImplementation({
                        ownerBinding: binding,
                        dependencyId,
                        requestCache,
                        supplierCache,
                        deferredCache,
                    });
                    deferredRequests.push(...dependency.deferredRequests);
                    return [dependency.value];
                })
            );

            HaywireMultiError.validateAllSettled(settled);

            const dependencies = settled.flatMap(settle => settle.value);
            const value = binding.isAsync
                ? await binding.provider(...dependencies)
                : binding.provider(...dependencies);

            validateProviderOutput(binding.outputId, value);

            // Record this instance so that any deferred bubbling up from a dependency
            // (which may circularly reference this very binding) re-uses it.
            // List element bindings only produce a portion of the list, so the full list is registered
            // by whichever caller collects the elements.
            if (!isListBinding) {
                for (const { registry } of deferredRequests) {
                    registry.set(binding.outputId.baseId(), { value });
                }
            }

            return [value];
        })();

        // After cache has been written to, we can await any promises that have been initialized.
        if (relevantCache) {
            // Note the cache value does not _immediately_ have `value` attached to it.
            // While risky, this is safe because it will only be accessed by the sync equivalent
            // if this async method was actually generated "eagerly" and therefore fully resolved.
            const cacheValue = Object.assign(cacheContainer, {
                promise: outputPromise
                    .then(async ([value]) => {
                        cacheValue.value = value;
                        await Promise.all(deferredPromises);
                        return [value] as const;
                    })
                    .catch((err: unknown) => {
                        // Failures may occur because of deferred dependencies,
                        // or because the actual generation promise rejects
                        // (which we still have not actually awaited and checked!)
                        // so if that does happen, we need to evict this value from cache.
                        if (relevantCache.get(binding) === cacheContainer) {
                            relevantCache.delete(binding);
                        }
                        throw err;
                    }),
            }) as {
                promise: Promise<[unknown]>;
                value: unknown;
            };

            relevantCache.set(binding, cacheValue);
        }

        const [value] = await outputPromise;

        return {
            value,
            deferredRequests,
        };
    }

    async #getIdImplementation({
        ownerBinding,
        dependencyId,
        requestCache,
        supplierCache,
        deferredCache,
    }: {
        ownerBinding: GenericBinding;
        dependencyId: GenericHaywireId;
        requestCache: ScopeCache;
        supplierCache: ScopeCache;
        deferredCache: DeferredCache;
    }): Promise<{
        value: unknown;
        deferredRequests: DeferredRequest[];
    }> {
        const dependencyBaseId = dependencyId.baseId();
        // If already created instance in same dependency chain, just re-use that one!
        const deferredValue = deferredCache.get(dependencyBaseId);
        if (deferredValue) {
            return {
                value: deferredValue.value,
                deferredRequests: [],
            };
        }

        const { supplier } = dependencyId.annotations;

        if (typeof supplier === 'object') {
            // Each supplier invocation is its own request: it always gets a fresh supplier-scope
            // cache, and only continues the owner's request scope when propagating. The owner's
            // "request scope" is its supplier cache when it is itself supplier-scoped.
            const relevantCache =
                ownerBinding.scope === isolatedRequestScope ? supplierCache : requestCache;
            if (supplier.sync) {
                return {
                    value: () => {
                        const scopeCache: ScopeCache = new Map();
                        return this.#getSyncId(
                            dependencyId,
                            supplier.propagateScope ? relevantCache : scopeCache,
                            scopeCache
                        );
                    },
                    deferredRequests: [],
                };
            }
            return {
                value: async () => {
                    const scopeCache: ScopeCache = new Map();
                    return this.#getMaybeSyncId(
                        dependencyId,
                        supplier.propagateScope ? relevantCache : scopeCache,
                        scopeCache
                    );
                },
                deferredRequests: [],
            };
        }

        const isList = checkIsList(dependencyId);

        let result: {
            value: unknown;
            deferredRequests: DeferredRequest[];
        };
        if (isList) {
            const dependencyBindings = this.#baseIdToListBindings.get(dependencyBaseId)!;
            // Collected in binding order (rather than pushing on completion) so results are consistent
            // regardless of which provider resolves first.
            const settled = await Promise.allSettled(
                dependencyBindings.map(async dependencyBinding =>
                    this.#isAsyncImplementationMap.get(dependencyBinding)!
                        ? this.#getImplementation({
                              binding: dependencyBinding,
                              requestCache,
                              supplierCache,
                              deferredCache,
                          })
                        : this.#getSyncImplementation({
                              binding: dependencyBinding,
                              requestCache,
                              supplierCache,
                              deferredCache,
                          })
                )
            );
            HaywireMultiError.validateAllSettled(settled);
            result = {
                value: settled.flatMap(({ value }) => value.value as unknown[]),
                deferredRequests: settled.flatMap(({ value }) => value.deferredRequests),
            };
        } else {
            const dependencyBinding = this.#baseIdToBinding.get(dependencyBaseId)!;
            result = this.#isAsyncImplementationMap.get(dependencyBinding)!
                ? await this.#getImplementation({
                      binding: dependencyBinding,
                      requestCache,
                      supplierCache,
                      deferredCache,
                  })
                : this.#getSyncImplementation({
                      binding: dependencyBinding,
                      requestCache,
                      supplierCache,
                      deferredCache,
                  });
        }

        const { value, deferredRequests } = result;
        for (const { registry } of deferredRequests) {
            registry.set(dependencyBaseId, { value });
        }
        return result;
    }

    /**
     * Synchronous version of `#getImplementation`. For the most part, logic is the same (just without promises)
     * and can defer to documentation in that method for detail.
     *
     * In general this method is preferred due to simplicitly (no promise race conditions) and to ensure sync support
     * for suppliers.
     *
     * @param params - required params
     * @param params.binding - binding being requested
     * @param params.requestCache - current request cache
     * @param params.supplierCache - current scope cache
     * @param params.deferredCache - map of any bindings that have been calculated already in the current request chain
     * @returns both the instantiated value, and any deferred requests that have been generated by dependencies
     * @throws if the provided value is not of the correct type (e.g. null but output is not nullable)
     */
    #getSyncImplementation({
        binding,
        requestCache,
        supplierCache,
        deferredCache,
    }: {
        binding: GenericBinding;
        requestCache: ScopeCache;
        supplierCache: ScopeCache;
        deferredCache: DeferredCache;
    }): {
        value: unknown;
        deferredRequests: DeferredRequest[];
    } {
        // Re-use of instances already created in the same request chain is handled by callers (see async version).
        const isListBinding = checkIsList(binding.outputId);

        const relevantCache = {
            [transientScope]: null,
            [eagerSingletonScope]: this.#singletonCache,
            [singletonScope]: this.#singletonCache,
            [eagerRequestScope]: requestCache,
            [requestScope]: requestCache,
            [isolatedRequestScope]: supplierCache,
        }[binding.scope];

        if (relevantCache) {
            const cached = relevantCache.get(binding);
            if (cached) {
                return {
                    value: cached.value,
                    deferredRequests: [],
                };
            }
        }

        const cacheContainer = {};

        const parameters: unknown[] = [];
        const deferredRequests: DeferredRequest[] = [];

        for (const dependencyId of binding.dependencyIds) {
            if (dependencyId.annotations.deferred) {
                const deferred = pDefer();
                const registry: DeferredCache = new Map();
                deferredRequests.push({
                    ...deferred,
                    binding,
                    dependencyId,
                    registry,
                    // If deferred dependencies fail, need to evict value from cache
                    // as it is not actually fully and safely instantiated.
                    // Note that async version skips this logic, because the cached promise
                    // performs a similar check to wait for deferred success.
                    reject: relevantCache
                        ? err => {
                              deferred.reject(err);
                              if (relevantCache.get(binding) === cacheContainer) {
                                  relevantCache.delete(binding);
                              }
                          }
                        : deferred.reject,
                });
                parameters.push(deferred.promise);
                continue;
            }

            const dependency = this.#getSyncIdImplementation(
                binding,
                dependencyId,
                requestCache,
                supplierCache,
                deferredCache
            );
            deferredRequests.push(...dependency.deferredRequests);
            parameters.push(dependency.value);
        }
        const value = binding.provider(...parameters);

        validateProviderOutput(binding.outputId, value);

        // Promise is not actually provided, since the _async_ version of this binding should never be called,
        // because we prefer sync version.
        // **NOTE** Opposite is not necessarily true. The async version does _eventually_ populate `value` because eager
        // scopes can transition from async -> sync.
        // Record this instance so that any deferred bubbling up from a dependency
        // (which may circularly reference this very binding) re-uses it.
        // List element bindings only produce a portion of the list (see async version).
        if (!isListBinding) {
            for (const { registry } of deferredRequests) {
                registry.set(binding.outputId.baseId(), { value });
            }
        }

        relevantCache?.set(binding, Object.assign(cacheContainer, { value }));
        return {
            value,
            deferredRequests,
        };
    }

    #getSyncIdImplementation(
        ownerBinding: GenericBinding,
        dependencyId: GenericHaywireId,
        requestCache: ScopeCache,
        supplierCache: ScopeCache,
        deferredCache: DeferredCache
    ): {
        value: unknown;
        deferredRequests: DeferredRequest[];
    } {
        const dependencyBaseId = dependencyId.baseId();
        const deferredValue = deferredCache.get(dependencyBaseId);
        if (deferredValue) {
            return {
                value: deferredValue.value,
                deferredRequests: [],
            };
        }

        const { supplier } = dependencyId.annotations;

        if (typeof supplier === 'object') {
            // Each supplier invocation is its own request: it always gets a fresh supplier-scope
            // cache, and only continues the owner's request scope when propagating. The owner's
            // "request scope" is its supplier cache when it is itself supplier-scoped.
            const relevantCache =
                ownerBinding.scope === isolatedRequestScope ? supplierCache : requestCache;
            if (supplier.sync) {
                return {
                    value: () => {
                        const scopeCache: ScopeCache = new Map();
                        return this.#getSyncId(
                            dependencyId,
                            supplier.propagateScope ? relevantCache : scopeCache,
                            scopeCache
                        );
                    },
                    deferredRequests: [],
                };
            }
            return {
                value: async () => {
                    const scopeCache: ScopeCache = new Map();
                    return this.#getMaybeSyncId(
                        dependencyId,
                        supplier.propagateScope ? relevantCache : scopeCache,
                        scopeCache
                    );
                },
                deferredRequests: [],
            };
        }

        const isList = checkIsList(dependencyId);

        let result: {
            value: unknown;
            deferredRequests: DeferredRequest[];
        };
        if (isList) {
            const bindings = this.#baseIdToListBindings.get(dependencyBaseId)!;
            const values: unknown[][] = [];
            const deferredRequests: DeferredRequest[][] = [];
            for (const binding of bindings) {
                const bindingResult = this.#getSyncImplementation({
                    binding,
                    requestCache,
                    supplierCache,
                    deferredCache,
                });
                values.push(bindingResult.value as unknown[]);
                deferredRequests.push(bindingResult.deferredRequests);
            }
            result = {
                value: values.flat(),
                deferredRequests: deferredRequests.flat(),
            };
        } else {
            const binding = this.#baseIdToBinding.get(dependencyBaseId)!;
            result = this.#getSyncImplementation({
                binding,
                requestCache,
                supplierCache,
                deferredCache,
            });
        }

        const { value, deferredRequests } = result;
        for (const { registry } of deferredRequests) {
            registry.set(dependencyBaseId, { value });
        }
        return result;
    }

    /**
     * Sync version of {@link preloadAsync}.
     *
     * Similar to `preload`, technically safe to invoke multiple times, but short-circuits on following requests
     * to improve performance.
     *
     * Ensures that container is wired before any loading.
     */
    #preload(): void {
        if (this.#preloaded) {
            return;
        }
        this.wire();

        const reqScope: ScopeCache = new Map();
        const requestSingleton = (binding: GenericBinding): void => {
            const dependencies = this.#singletonMap.get(binding)!;
            for (const dependency of dependencies) {
                requestSingleton(dependency);
            }
            this.#getSync({ bindings: binding, requestCache: reqScope, supplierCache: reqScope });
        };
        for (const binding of this.#singletonMap.keys()) {
            requestSingleton(binding);
        }

        this.#preloaded = Promise.resolve();
    }

    /**
     * Expose private field via a symbol to provide close to private functionality,
     * while still being accessible in the same file so it can be properly exposed in the {@link SyncContainer}.
     *
     * @returns normally private preload reference.
     */
    protected get [preloadSyncSym](): () => void {
        return this.#preload.bind(this);
    }

    /**
     * Handle the top-level request for an instance.
     * Attempts to defer to sync version if possible.
     *
     * If it is the beginning of a request (rather than a scope-propagating supplier) instantiate all eager requests first.
     *
     * Then create the actual instance, and resolve any deferred requests that result.
     * This resolution will kick off its own recursive requests to `#getMaybeSync`, and while the base case is not explicitly
     * stated, this is safe because of prior checks ensure the container has a healthy setup.
     *
     * @param bindings - requested binding(s). Pass multiple bindings to compute a list.
     * Takes binding instead of id to support precompute steps where only some bindings require instantiation.
     * @param requestCache - current request cache, shared across entire request
     * @param supplierCache - current scope cache, potentially same as requestCache,
     * which can be used to determine if request singletons need to be instantiated first
     * @param deferredCache - map of any bindings that have been calculated already in the current request chain,
     * to be passed to actual implementations.
     * @returns promise of instantiated value, with all deferred values resolved
     */
    async #getMaybeSync(
        bindings: GenericBinding | readonly GenericBinding[],
        requestCache: ScopeCache,
        supplierCache: ScopeCache,
        deferredCache?: DeferredCache
    ): Promise<unknown> {
        const bindingsList = [bindings].flat();

        if (requestCache === supplierCache && !deferredCache) {
            // If the caches are the same, this is a "top level" request. Note that could be either
            // a `container.get()` _or_ a supplier that does not propagate scope. Either one will
            // require all eager request instances to be create before the rest of dependency chain can begin.
            const settled = await Promise.allSettled(
                // Note: the outer callback must _not_ be `async`. flatMap only flattens a
                // returned array, not a promise of one, so an async callback would leave the
                // inner eager requests unawaited.
                bindingsList.flatMap(binding =>
                    this.#requestMap
                        .get(binding)!
                        .map(async eagerBinding =>
                            this.#getMaybeSync(eagerBinding, requestCache, supplierCache)
                        )
                )
            );

            HaywireMultiError.validateAllSettled(settled);
        }
        const chainDeferredCache =
            deferredCache ?? new Map<GenericBaseHaywireId, { value: unknown }>();

        // If this instance could be implemented entire synchronously, do it.
        // Note this logic has to come _after_ the eager requests, because the async implementation map
        // relies on the logic that these values do already exist.
        if (!bindingsList.some(binding => this.#isAsyncImplementationMap.get(binding))) {
            // Pass `bindings` (not `bindingsList`) to preserve single-vs-array semantics:
            // `#getSync` flattens to an array only when handed an array.
            return this.#getSync({
                bindings,
                requestCache,
                supplierCache,
                deferredCache: chainDeferredCache,
            });
        }

        // Create the requested value, which creates+validates all dependencies internally.
        // However, it may include "deferred" dependencies values as well, which are not yet created.
        // So create those next.
        const allResults = await Promise.allSettled(
            bindingsList.map(async binding =>
                this.#getImplementation({
                    binding,
                    requestCache,
                    supplierCache,
                    deferredCache: chainDeferredCache,
                })
            )
        );
        HaywireMultiError.validateAllSettled(allResults);
        const listValue: unknown[] = [];
        const deferredRequests: DeferredRequest[] = [];
        for (const bindingResult of allResults) {
            listValue.push(bindingResult.value.value);
            deferredRequests.push(...bindingResult.value.deferredRequests);
        }
        const value = collectRequestedValue(bindings, listValue, deferredRequests);

        try {
            const settled = await Promise.allSettled(
                deferredRequests.map(async deferredRequest => {
                    const { binding, dependencyId, registry } = deferredRequest;
                    const { supplier } = dependencyId.annotations;
                    const dependencyBaseId = dependencyId.baseId();
                    const chainCache = new Map([...chainDeferredCache, ...registry]);
                    const cachedValue = chainCache.get(dependencyBaseId);
                    if (cachedValue && typeof supplier !== 'object') {
                        // Already created in this request chain (e.g. circular reference), re-use it.
                        deferredRequest.resolve(cachedValue.value);
                        return;
                    }
                    const dependencyBindings = checkIsList(dependencyId)
                        ? this.#baseIdToListBindings.get(dependencyBaseId)!
                        : this.#baseIdToBinding.get(dependencyBaseId)!;
                    if (typeof supplier === 'object') {
                        const relevantCache =
                            binding.scope === isolatedRequestScope ? supplierCache : requestCache;
                        if (supplier.sync) {
                            deferredRequest.resolve(() => {
                                const scopeCache: ScopeCache = new Map();
                                return this.#getSync({
                                    bindings: dependencyBindings,
                                    requestCache: supplier.propagateScope
                                        ? relevantCache
                                        : scopeCache,
                                    supplierCache: scopeCache,
                                });
                            });
                        } else {
                            deferredRequest.resolve(async () => {
                                const scopeCache: ScopeCache = new Map();
                                return this.#getMaybeSync(
                                    dependencyBindings,
                                    supplier.propagateScope ? relevantCache : scopeCache,
                                    scopeCache
                                );
                            });
                        }
                    } else {
                        // Repeat the request cycle, because this value itself may invoke it's own
                        // deferred requests which need handling.
                        const val = await this.#getMaybeSync(
                            dependencyBindings,
                            requestCache,
                            supplierCache,
                            chainCache
                        );
                        deferredRequest.resolve(val);
                    }
                })
            );

            HaywireMultiError.validateAllSettled(settled);
        } catch (err) {
            // Generally speaking, the failure to invoke any deferred value means the entire dependency chain failed.
            // e.g. A depends on deferred dependencies of B + C.
            // B was successful, but C was not.
            // We still need to fail `B` because it may circularly reference, which has failed.
            for (const { reject } of deferredRequests) {
                reject(err);
            }
            throw err;
        }

        return value;
    }

    async #getMaybeSyncId(
        id: GenericHaywireId,
        requestCache: ScopeCache,
        supplierCache: ScopeCache
    ): Promise<unknown> {
        const baseId = id.baseId();
        return this.#getMaybeSync(
            checkIsList(baseId)
                ? this.#baseIdToListBindings.get(baseId)!
                : this.#baseIdToBinding.get(baseId)!,
            requestCache,
            supplierCache
        );
    }

    /**
     * Sync version of `#getMaybeSync`. Because deferred values use promises, it is actually impossible to _really_
     * resolve them in the same event loop as returning this instance. However, they will be resolved on the next event loop.
     *
     * Fundamentally this is acceptable, as deferred dependencies should be treated as _eventually_ resolving anyways.
     *
     * @param params - required params
     * @param params.bindings - requested binding(s). Pass multiple bindings to compute a list.
     * Takes binding instead of id to support precompute steps where only some bindings require instantiation.
     * @param params.requestCache - current request cache
     * @param params.supplierCache - current scope cache
     * @param params.deferredCache - map of any bindings that have been calculated already in the current request chain
     * @returns instantiated value, with all deferred requests immediately resolving on the next event loop.
     * If provided array of bindings, returns a single array of all results merged.
     * @throws if instantiation of providers fails, or when one of the deferred chains fails after instantiation
     */
    #getSync({
        bindings,
        requestCache,
        supplierCache,
        deferredCache,
    }: {
        bindings: GenericBinding | readonly GenericBinding[];
        requestCache: ScopeCache;
        supplierCache: ScopeCache;
        deferredCache?: DeferredCache;
    }): unknown {
        const bindingsList = [bindings].flat();

        if (requestCache === supplierCache && !deferredCache) {
            for (const binding of bindingsList) {
                for (const eagerBinding of this.#requestMap.get(binding)!) {
                    this.#getSync({ bindings: eagerBinding, requestCache, supplierCache });
                }
            }
        }

        const chainDeferredCache =
            deferredCache ?? new Map<GenericBaseHaywireId, { value: unknown }>();

        const listValue: unknown[] = [];
        const deferredRequests: DeferredRequest[] = [];
        for (const binding of bindingsList) {
            const bindingResult = this.#getSyncImplementation({
                binding,
                requestCache,
                supplierCache,
                deferredCache: chainDeferredCache,
            });
            listValue.push(bindingResult.value);
            deferredRequests.push(...bindingResult.deferredRequests);
        }
        const value = collectRequestedValue(bindings, listValue, deferredRequests);

        try {
            for (const deferredRequest of deferredRequests) {
                const { binding, dependencyId, registry } = deferredRequest;
                const { supplier } = dependencyId.annotations;
                const dependencyBaseId = dependencyId.baseId();
                const chainCache = new Map([...chainDeferredCache, ...registry]);
                const cachedValue = chainCache.get(dependencyBaseId);
                if (cachedValue && typeof supplier !== 'object') {
                    // Already created in this request chain (e.g. circular reference), re-use it.
                    deferredRequest.resolve(cachedValue.value);
                    continue;
                }
                const dependencyBindings = checkIsList(dependencyId)
                    ? this.#baseIdToListBindings.get(dependencyBaseId)!
                    : this.#baseIdToBinding.get(dependencyBaseId)!;
                if (typeof supplier === 'object') {
                    const relevantCache =
                        binding.scope === isolatedRequestScope ? supplierCache : requestCache;
                    if (supplier.sync) {
                        deferredRequest.resolve(() => {
                            const scopeCache: ScopeCache = new Map();
                            return this.#getSync({
                                bindings: dependencyBindings,
                                requestCache: supplier.propagateScope ? relevantCache : scopeCache,
                                supplierCache: scopeCache,
                            });
                        });
                    } else {
                        deferredRequest.resolve(async () => {
                            const scopeCache: ScopeCache = new Map();
                            return this.#getMaybeSync(
                                dependencyBindings,
                                supplier.propagateScope ? relevantCache : scopeCache,
                                scopeCache
                            );
                        });
                    }
                } else {
                    const val = this.#getSync({
                        requestCache,
                        supplierCache,
                        bindings: dependencyBindings,
                        deferredCache: chainCache,
                    });
                    deferredRequest.resolve(val);
                }
            }
        } catch (err) {
            for (const { reject } of deferredRequests) {
                reject(err);
            }
            throw err;
        }

        return value;
    }

    #getSyncId(id: GenericHaywireId, requestCache: ScopeCache, supplierCache: ScopeCache): unknown {
        const baseId = id.baseId();
        return this.#getSync({
            bindings: checkIsList(baseId)
                ? this.#baseIdToListBindings.get(baseId)!
                : this.#baseIdToBinding.get(baseId)!,
            requestCache,
            supplierCache,
        });
    }

    /**
     * Expose private field via a symbol to provide close to private functionality,
     * while still being accessible in the same file so it can be properly exposed in the {@link SyncContainer}.
     *
     * @returns normally private getSync method
     */
    protected get [getSyncSym](): (
        id: GenericHaywireId,
        requestCache: ScopeCache,
        supplierCache: ScopeCache
    ) => unknown {
        return this.#getSyncId.bind(this);
    }

    protected get [getIdToBindingSym](): ReadonlyMap<GenericOutputHaywireId, GenericBinding> {
        return this.#idToBinding;
    }

    protected get [getIdToListBindingsSym](): ReadonlyMap<
        GenericOutputHaywireId,
        readonly GenericBinding[]
    > {
        return this.#idToListBindings;
    }
}

/**
 * Extension of Container that also supports all methods in a synchronous manner.
 * Also supports async for general consistency, although all computation is fundamentally synchronous under the hood.
 *
 * @see {@link Container} for more documentation
 *
 * @template Outputs
 */
export class SyncContainer<Outputs extends [Extendable]> extends Container<Outputs> {
    /**
     * Create a synchronous container from module bindings.
     *
     * @param bindings - module bindings to create container from
     * @param listBindings - map of base id to list bindings
     * @returns synchronous container (that also supports async)
     */
    public static override [createContainerSym]?<Outputs extends [Extendable]>(
        bindings: ReadonlyMap<GenericBaseHaywireId, GenericBinding>,
        listBindings: ReadonlyMap<GenericBaseHaywireId, readonly GenericBinding[]>
    ): SyncContainer<Outputs> {
        return new SyncContainer<Outputs>(bindings, listBindings);
    }

    /**
     * Sync version of {@link preloadAsync}.
     *
     * Instantiates all eager singletons.
     */
    public preload(): void {
        this[preloadSyncSym]();
    }

    /**
     * Sync version of {@link get}.
     *
     * Type checking enforces that the requested identifier exists in the container, and translates requested id to response type.
     *
     * Will preload all singletons if not already done.
     */
    public get<Id extends GenericHaywireId>(
        id: Id,
        ...invalidInput: [] &
            ([
                NonExtendable<
                    RawType<Id>,
                    Id['construct'],
                    Id['annotations']['named'],
                    Id['annotations']['list'] extends 'multi' | true ? true : false,
                    Id['annotations']['nullable'],
                    Id['annotations']['undefinable']
                >,
            ] extends Outputs
                ? []
                : [InvalidInput<'NoBindingExists'>])
    ): HaywireIdType<OutputHaywireId<Id>>;
    public get<Constructor extends IsClass>(
        clazz: Constructor,
        ...invalidInput: [] &
            ([
                NonExtendable<InstanceOfClass<Constructor>, Constructor, null, false, false, false>,
            ] extends Outputs
                ? []
                : [InvalidInput<'NoBindingExists'>])
    ): InstanceOfClass<Constructor>;
    public get<Id extends GenericHaywireId>(idOrClass: Id): HaywireIdType<OutputHaywireId<Id>> {
        const id = normalizeOutputId(unsafeIdentifier(idOrClass));
        const hasBindings = id.annotations.list
            ? this[getIdToListBindingsSym].has(id)
            : this[getIdToBindingSym].has(id);
        if (!hasBindings) {
            throw new HaywireProviderMissingError([id]);
        }
        this[preloadSyncSym]();
        const requestCache: ScopeCache = new Map();
        return this[getSyncSym](id, requestCache, requestCache) as HaywireIdType<
            OutputHaywireId<Id>
        >;
    }
}

export type GenericContainer = Container<[Extendable]>;

export const isSyncContainer = <Outputs extends [Extendable]>(
    container: Container<Outputs>
): container is SyncContainer<Outputs> => container instanceof SyncContainer;

export const createSyncContainer = SyncContainer[createContainerSym]!;
delete SyncContainer[createContainerSym];

export const createAsyncContainer = Container[createContainerSym]!;
delete Container[createContainerSym];

export const addBoundInstances = Container[addBoundInstancesSym]!;
delete Container[addBoundInstancesSym];
